LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_ARM_MODE := arm
LOCAL_MODULE := luajit
LOCAL_SRC_FILES := libluajit-$(TARGET_ARCH_ABI).a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := lua
LOCAL_STATIC_LIBRARIES := luajit
LOCAL_ARM_MODE := arm
LOCAL_CFLAGS := -O3 -shared -std=c99 -DLUA_USE_DLOPEN
LOCAL_SRC_FILES := luajava.c
include $(BUILD_SHARED_LIBRARY)
